### ISSUE TITLE
Now, How can I get menu_proxy_code_id?

### ISSUE THREAD

**Issue by przbadu** [ruckus/quickeebooks#100]
How can I get menu_proxy_code_id? I have no idea. 

I tried to generate menu_proxy_code_id while generating realm_id, access_token and access_secrete like:

``` ruby
at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    access_token = at.token
    access_secret = at.secret
    realm_id = params['realmId']

    menu_proxy_code_id = at.menu_proxy_code_id
```

but it will generate something like:

``` ruby
NoMethodError - undefined method `menu_proxy_code_id' for #<OAuth::AccessToken:0xb4eac7c>:
```

What i am missing here. Please make me clear, how can I generate menu_proxy_code_id and display contents of the bluedot menu.

============= thanks in advance ===================

**Comment by ruckus** [comment]
I mentioned in a previous Issue comment what you have to do:

https://github.com/ruckus/quickeebooks/issues/99#issuecomment-23720639

You need to make an API call to Intuit to fetch the menu proxy contents (and should cache them).

**Comment by ruckus** [comment]
In my example `menu_proxy_code_id` is MY cache key - its a product of my application and has nothing to do with Intuit. In my case its basically:

``` ruby
class IntuitAccount < ActiveRecord::Base
  def menu_proxy_code_id
    "ia-menu-#{id}-#{realm_id}"
  end
end
```

**Comment by przbadu** [comment]
Thanks a lot...the solution was on your previous code only...I have not concentrated on that part:

``` ruby
def bluedot
    access_token = current_company.access_token
    access_secret = current_company.access_secret
    consumer = OAuth::AccessToken.new($qb_oauth_consumer, access_token, access_secret)
    response = consumer.request(:get, "https://appcenter.intuit.com/api/v1/Account/AppMenu")
    if response && response.body
      html = response.body

      render(:text => html) and return
    end
end
```

other codes were to catche the result. Thanks rackus.
