### ISSUE TITLE
Support for Estimate service

### ISSUE THREAD

**Issue by swanandp** [ruckus/quickeebooks#103]
Is there any plan to add support for the Estimate service?

**Comment by ruckus** [comment]
Entity updates are usually done on "as-needed" basis and frankly I have no need for Esimate, so I don't see myself implementing it in the near future.

Feel free to implement it and send a Pull Request. Fortunately adding entities / endpoints is pretty straight-forward. You can generally just copy an existing endpoint and make some slight changes.

**Comment by swanandp** [comment]
Thanks for the clean code, I got a working code with Estimate entity today. I'll send a PR soon when I add a few more tests. Initial commit for that can be seen [here](https://github.com/swanandp/quickeebooks/commit/c00a8df31361ae9af141197a3f9cc77d7983523f)

**Comment by cwoolum** [comment]
Hey @swanandp , any chance you could get the pull request in? The estimate functionality would be helpful.

**Comment by swanandp** [comment]
Hi @cwoolum I think I am not fully ready to send a PR yet, but you can check out the changes here: https://github.com/swanandp/quickeebooks/compare/ruckus:master...master

I had to add in some hacks to get QB Desktop get working, the API seemed very quirky to me at that time.

**Comment by swanandp** [comment]
Closing this.
