### ISSUE TITLE
How to grep SalesTerm values  from QBO to our application

### ISSUE THREAD

**Issue by mrsowmya** [ruckus/quickeebooks#110]
![screenshot from 2013-10-21 15 27 50](https://f.cloud.github.com/assets/5724599/1371323/ca60c68a-3a37-11e3-9e2a-4225ffadbaab.png)
![screenshot from 2013-10-21 15 28 52](https://f.cloud.github.com/assets/5724599/1371324/d1d1ace0-3a37-11e3-8482-32ec0fe697f8.png)

You have not defined Term model. please let me know how to grep terms values from QBO. now i can only grep sales_term_id but i want sales_term_name.

This feature is available in windows, please make it available for online also

xml_accessor :sales_term_name, :from => 'SalesTermName'

**Comment by ruckus** [comment]
I just released `0.1.22` which adds support for `Online#SalesTerm`.

You can fetch a list of sales terms by calling:

``` ruby
service = Quickeebooks::Online::Service::SalesTerm.new
service.access_token = token
service.realm_id = realm_id
results = service.list
```

**Comment by mrsowmya** [comment]
Thank you.

**Comment by ruckus** [comment]
This is an intermittent error we get from Intuit and has nothing to do with Quickeebooks. Handling it could be better - its been an ongoing conversation on an Issue thread.

**Comment by ruckus** [comment]
Were you able to get this going?

**Comment by mrsowmya** [comment]
yes

On Tue, Oct 22, 2013 at 9:24 PM, Cody Caughlan notifications@github.comwrote:

> Were you able to get this going?
> 
> On Oct 22, 2013, at 4:37 AM, mrsowmya notifications@github.com wrote:
> 
> > Thank you.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ruckus/quickeebooks/issues/110#issuecomment-26815853
> .

## 

Thanks :

Sowmya. M. R
