### ISSUE TITLE
Search customer by Email

### ISSUE THREAD

**Issue by drc37** [ruckus/quickeebooks#117]
Is there a way search Customer record by email. I have scoured the internet trying to find a way to do it. Since it is a child record, I haven't found a way to do it yet. 

Is there a way to do it?

David

**Comment by ruckus** [comment]
I don’t think so. Intuit will only allow you to filter/search by the fields they directly support in their “Filter” documentation.

Which on another note I cannot find. Its been completely removed from https://developer.intuit.com/docs

I cannot for the life of me find the Desktop v2 API docs.

**Comment by ruckus** [comment]
Ok I found the docs for QBD Customer:

https://developer.intuit.com/docs/95_deprecated/qbd_v2/qbd_v2_reference/0600_object_reference/customer

If you scroll down to the "CustomerQuery Attributes" section you'll see what is supported. Unfortunately email is not.

**Comment by drc37** [comment]
Thanks for helping me with that. 

David
