### ISSUE TITLE
API Token and secret

### ISSUE THREAD

**Issue by timsaunders** [ruckus/quickeebooks#13]
Hi,

Are you able to give me any direction on how to obtain a Quickbooks Online Access token and secret for using this gem? Much help would be appreciated.

Thanks
Tim.

**Comment by ruckus** [comment]
Hi Tim,

You'll need to create an application which integrates with Intuit Data Services (its free to create an app but you later pay a small connection fee per client, I think its $5/month?).

See the documentation here:

https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services

When you register and create your app you will receive YOUR access token & secret. That is, you put your token & secret in the OAuth consumer call:

qb_oauth_consumer = OAuth::Consumer.new(your_consumer_key, your_consumer_secret, ..... )

The other component is the OAuth token that you get from each of your connected users, which they supply to you during the connection process, see:

https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0025_Intuit_Anywhere

Step 2 is where you get the access token from Intuit - which you then use in your app. Once you have a connected users token & secret and with YOUR token & secret they all come together like:

token = OAuth::AccessToken.new(qb_oauth_consumer, user_access_token, user_access_secret)

At this point you can use the "token" object to make authenticated calls.

Get started by creating your App Profile: https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0025_Intuit_Anywhere/0020_Connect/Create_An_App_Profile

I hope this helps.

Cheers,
/Cody

**Comment by timsaunders** [comment]
Thanks for the response Cody, and the steps to help get connected!!

I know I shouldn't be asking you Quickbooks questions, however I have had
trouble getting support with them. :) However for some reason I can't see
the Create an App button within my profile, do you know if there is
something I need to setup before I am allowed to create apps?The only menu
items I have are Launch my apps, Manage my apps, Edit Company Settings,
Manage Users.

Little lost to where to create apps within the app center??

Thanks again!
Tim.

**Comment by ruckus** [comment]
No problem.

So when I go to: https://workplace.intuit.com/Account/Logon?startWithLogOn=true

and then log-in I am taken to https://workplace.intuit.com/Home/DevHome and my screen looks like: http://cl.ly/image/2Y0M410g2l2O  and one can create new apps by clicking on the "Create" tab.

Do you not see this?

You should be able to create new apps - there is no holding period or anything.

Cheers,
/Cody

**Comment by timsaunders** [comment]
Yeah that's weird, whenever I login my account it goes to
https://workplace.intuit.com/Home/MyApps instead of
https://workplace.intuit.com/Home/DevHome.

Here is a screen shot of my menu bars (Not sure if it will come through on
this github email).

Do you have any good contacts at Quickbooks I could ask. I noticed several
other people have had the same issue.

http://community.intuit.com/posts/how-do-i-create-a-new-app

Thanks
Tim.

**Comment by ruckus** [comment]
Did you create your account from here:

https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0025_Intuit_Anywhere/0010_SignUp/0010_Register_With_IDN

and then the next section titled "Create an Intuit App Center Account" (see navigation on left)?

Give that a shot.

As for contacts at Intuit - no I dont have any. I've used the developer forums in the past, and they're alright. Fortunately I have not had to contact Intuit Support but from what I have heard, yes, it can be byzantine.

/Cody

**Comment by timsaunders** [comment]
Thanks for your help Cody!! I finally keep playing around with it and
creating accounts with multiple login details and now it shows that same
top menu bar that you showed me! Not sure what I did to make it work, but
it works! :)

Thanks, and I look forward to using your gem that you have created.
Tim.

**Comment by shamabbas** [comment]
First of all, thanks alot Ruckus for all your help through this code. I'm able to connect with my app in QuickBooks and complete the authorization. I wasn't able to redirect back to my application after authorization but I added oauthcall back url to my app's method. Now is working. Next, I'll save the user details, token etc into my app's DB but two more things I need to retrieve User's INVOICE and CONTACTS from their QuickBooks account. I tried your code "Quickeebooks::Online::Service::Invoice" but its not working for me, asks for two parameters and I mention key and secret but doesn't work. I copied this plugin into my app/lib as well. Seems like it can read Library  quickbook->online>services>invoice but not retrieving any data. I'm sure I'm missing something?

Can you help me with it? I'll be grateful to you :-)

Thanks.

**Comment by shamabbas** [comment]
I guess problem was, Instead of realmId I was using real_id. :-) Now seems to be working.
Thanks :-)
