### ISSUE TITLE
Issue with Item creation

### ISSUE THREAD

**Issue by jimiguru** [ruckus/quickeebooks#132]
When trying to create an item, getting an IntuitRequestException.

It appears the only required fields in the Item model are:

:name and :account_reference => IncomeAccountRef

However on the V2 QB API reference, they don't specify IncomeAccountRef as required, rather AccountId instead.

**Comment by jimiguru** [comment]
After examining the API reference further, looks like everything is correct.

Can't seem to get a simple item created though.

```
  item = Quickeebooks::Online::Model::Item.new
  item.name = "Test"
  account_ref = Quickeebooks::Online::Model::AccountReference.new
  account_ref.account_id = Quickeebooks::Online::Model::Id.new(30)
  item.account_reference = account_ref
  item_service.create(item)
```

**Comment by ruckus** [comment]
Whats the request and response XML look like?

**Comment by jimiguru** [comment]
Well, I updated the Gem to gain the XML data feature that was merged in last month and the issue went away and I can create Items now.

Thanks!
