### ISSUE TITLE
Using a number filter doesn't correctly set the value

### ISSUE THREAD

**Issue by kdaigle** [ruckus/quickeebooks#18]
When I'm using a number filter, the "value" isn't ever set in the code. Normally, the filters expect a value to be passed in as an attribute on the hash. But with `gt` and `lt` the "value" is the value of that key.

You have code to manage the switching but it still uses `@value` where it should be using `@gt` or `@lt` for the value.

I've cheated by also passing a `:value` directly in as well. For example: `Quickeebooks::Online::Service::Filter.new(:number, :field => "OpenBalance", :gt => 0, :value => 0)`

If I have time today, I'll pull down and make the change and offer a PR along with this. But I wanted to put this here so I wouldn't forget and so anyway else can see the "quick fix".

**Comment by ruckus** [comment]
According to the Intuit docs at https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0400_QuickBooks_Online/0100_Calling_Data_Services/0030_Retrieving_Objects

I don't even see support for `:GreaterThan:` and `:LessThan:` operator support - so I have no clue where I pulled that from.

**Comment by kdaigle** [comment]
Hmm, I wonder if they got deprecated? I can't seem to find them either but I'm sure they used to exist. Not sure what to do about this issue now...

**Comment by ruckus** [comment]
It must have been deprecated - I'd be surprised if I pulled that out of thin air. But stranger things have happened.

Anyways - I should probably tweak the logic to at least support the `:eq` method the way you indicate:

``` ruby
Quickeebooks::Online::Service::Filter.new(:number, :field => "OpenBalance", :eq => 50)
```

**Comment by kdaigle** [comment]
I wouldn't remove the `:gt` or `:lt` because they seem to be working/accepted. Let me throw together some quick code for this.

**Comment by ruckus** [comment]
Oh really, those operators still work against the Intuit API but they are just not documented? Interesting. I guess I am not surprised, the docs are terrible.

**Comment by kdaigle** [comment]
@ruckus here is the PR. So let me know if you want me to change anything.

**Comment by kdaigle** [comment]
The PR was merged in to fix this.
