### ISSUE TITLE
Setting static base_url doesn't seem to work?

### ISSUE THREAD

**Issue by MattRogish** [ruckus/quickeebooks#22]
Hi,

Per the Intuit docs here:
https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0400_QuickBooks_Online/0100_Calling_Data_Services/0010_Getting_the_Base_URL

It says we can use a hard-coded base URL of "https://qbo.sbfinance.intuit.com"

If we do this on the Service that we create, I start getting IntuitRequestExceptions. Any idea why? Would like to avoid the extra HTTP request.

Thanks!
## 

Matt

**Comment by ruckus** [comment]
Very interesting. Yes, this will save an HTTP call. It appears this is a new-ish feature. 

Anyways, I got it to work on my end. I'll patch up Quickeebooks and push out a release. Although I probably wont get a chance to do this until tomorrow or so.

**Comment by MattRogish** [comment]
For some reason our implementation is failing, any quick notes on how to (possibly temporarily) use the  base_url to make it work? Or is it quite a bit of effort?

Thanks,

## 

Matt

**Comment by ruckus** [comment]
Not a lot of effort at all. In online service_base#initialize just set @base_uri = to the Http host. I'm out of town for rest of day, but can do it formally tomorrow

**Comment by ruckus** [comment]
Hi @MattRogish  - I just pushed to master and released `0.1.0` version of the gem which implements the static base URL. Thanks for bringing this to my attention, its always great to shave off an API call.

**Comment by MattRogish** [comment]
THANKS!
