### ISSUE TITLE
DateTime vs. Date in Filters

### ISSUE THREAD

**Issue by MattRogish** [ruckus/quickeebooks#35]
I was just noticing that we use @type key :date and :datetime in creating a filter, but their semantic meaning are ignored; the filter output value is passed thru formatted_time which formats based on @value.class. 

However #date_time_to_s validates that the objects are Time/DateTime. There's a spec that passes a Date object directly which seems to pass only because :value doesn't do the Time/DateTime validation.

It seems it might be more consistent if the validation and the output formatting was performed based on @type (date validates/formats Date, DateTime validates/formats date and time) and not @value.class. I started doing this in a PR (it's a pretty easy refactor), but stopped when I broke that spec mentioned above.

I didn't want to accidentally break anything by this refactor, so I aborted. Thoughts? cc @ruckus  Thanks!

**Comment by ruckus** [comment]
Yeah I think you're right - that would clear up any ambiguity and also remove the need for the `if` check in `formatted_time` - we would just make `format_date` and `format_datetime` methods.

Is that how you started to implement your refactor? Or maybe you had a better way...

**Comment by ruckus** [comment]
Good idea and I finally just implemented this in 9d649f7fa64f3781b14d2329700d7a169905b3a4
