### ISSUE TITLE
Close Quickbooks connect popup window and redirect

### ISSUE THREAD

**Issue by bcackerman** [ruckus/quickeebooks#45]
Is it possible to close the window automatically that is opened to connect a users' Quickbooks connect when finishing?

**Comment by ruckus** [comment]
This is outside the scope of Quickeebooks and its up to the hosting application to control that.

In my OAuth callback view I have a snippet like this (HAML code but should be clear enough)

```
- if @success
  %h3 You have successfully connected to Intuit
  %p This window will close automatically.
  %script
    = "opener.parent.location.reload(true);"
    = "setInterval(function() {window.close()}, 2000);"
```

**Comment by bcackerman** [comment]
Thanks
