### ISSUE TITLE
Retrieve last saved object?

### ISSUE THREAD

**Issue by bcackerman** [ruckus/quickeebooks#50]
Is there a way to retrieve the last saved ID for a customer I just created in Quickbooks?

**Comment by ruckus** [comment]
Yes, you can read this value from the create response success object.

The response structure is: http://docs.developer.intuit.com/0025_Intuit_Anywhere/0050_Data_Services/v2/0500_QuickBooks_Windows/0600_Object_Reference/Customer#Creating_a_Customer

So you can access the "Id" value like:

response = customer_service.create(customer)
 => #<RestResponse>: Success[CustomerAdd] @ 2013-03-25 02:29:49 UTC

new_customer_id = response.success.party_role_ref.id.value

**Comment by bcackerman** [comment]
Thanks!

**Comment by bcackerman** [comment]
Quick question, if I wanted to save something in the address.line1 in a QB online customer object (https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0400_QuickBooks_Online/Customer) what would I use instead of customer.address.list1 ?

**Comment by ruckus** [comment]
I don't understand your question, can you please clarify?

**Comment by bcackerman** [comment]
So I'm looking to save a company name into quickbooks address.line1 that you can see here:  https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0400_QuickBooks_Online/Customer

In my code I have `customer.address.list1 = c.company` but that's not correct.  Do you know how to set a value into the list1 field?

**Comment by ruckus** [comment]
Ok I see. The recommended approach is to instantiate a `Address` object and then assign it to the `Customer`, like so:

``` ruby
customer = Quickeebooks::Windows::Model::Customer.new
customer.type_of = "Person"
customer.name = "Acme Plumbing"

address = Quickeebooks::Windows::Model::Address.new
address.line1 = "323 Steiner St."
address.line2 = "Suite 204"
address.city = "San Francisco"
address.postal_code = "94117"
address.country_sub_division_code = "CA"
address.tag = "Billing"

customer.address = address
```

**Comment by bcackerman** [comment]
Oh! Got it, thanks!

**Comment by bcackerman** [comment]
Does this work for Online as well?  Because I receive 

``` ruby
undefined method `list1=' for #<Quickeebooks::Online::Model::Address:0x007ffb5584a000>
```

 when I do

``` ruby
address = Quickeebooks::Online::Model::Address.new
address.list1 = c.company
```

**Comment by ruckus** [comment]
The convenience method on `Online::Customer#address=` didn't exist, but I just added it to `0.1.5` and pushed out the new gem.

That being said, I'm not sure what your `list1` method is - you have referred to it before and I assume you mean `line1`?

**Comment by bcackerman** [comment]
Thanks for the update! So I'm getting `line1` from the Customer object docs here: https://ipp.developer.intuit.com/0010_Intuit_Partner_Platform/0050_Data_Services/0400_QuickBooks_Online/Customer

**Comment by bcackerman** [comment]
And that's what I want to store the company name in to send to Quickbooks Online

**Comment by ruckus** [comment]
Yes, its line1. But in your prior emails you kept referring to "list1" - but I assume you meant "line1" ?

**Comment by bcackerman** [comment]
Oh!!! Jeez I'm need to sleep or something, sorry!

**Comment by bcackerman** [comment]
Sorry for being a nuisance but I now get an error setting the `CountrySubDivisionCode` in address.  The error is 

``` ruby
undefined method 'countrysubdivisioncode=' for #<Quickeebooks::Online::Model::Address:0x007fcd27d2d858>
```

**Comment by ruckus** [comment]
The correct attribute name is `country_sub_division_code` (notice the underscores). 

Quickeebooks uses underscored property names from Intuit camelCase names. 

So Intuit says `PostalCode` and the corresponding Quickeebooks model attribute is `postal_code`

If you're unsure you can always have a look at the actual Quickeebooks model definition, which for `Address` is here:

https://github.com/ruckus/quickeebooks/blob/master/lib/quickeebooks/online/model/address.rb

**Comment by bcackerman** [comment]
Ah ok, thanks.  I might add some more details to this readme for others too.

**Comment by bcackerman** [comment]
I now receive the error: `undefined method 'address=' for #<Quickeebooks::Online::Model::Customer:0x007fcd27fe21c0>
` where I try to set `customer.address = address`

``` ruby
def export_customers(account, oauth_client)
        account.customers.each do |c|
            customer_service = Quickeebooks::Online::Service::Customer.new
            customer_service.access_token = oauth_client
            customer_service.realm_id = account.quickbooks_realm_id

            customer = Quickeebooks::Online::Model::Customer.new
            customer.name = c.full_name
            customer.email = c.email
            address = Quickeebooks::Online::Model::Address.new
            address.line1 = c.company
            address.line2 = c.address1
            address.line3 = c.address2
            address.city = c.city
            address.country_sub_division_code = c.state
            address.postal_code = c.zip
            phone = Quickeebooks::Online::Model::Phone.new
            phone.device_type = "Phone"
            phone.free_form_number = c.phone
            fax = Quickeebooks::Online::Model::Phone.new
            fax.device_type = "Fax"
            fax.free_form_number = c.fax

            customer.address = address
            customer.phone = phone
            customer.fax = fax

            response = customer_service.create(customer)
            Rails.logger.info response

            c.quickbooks_id = response.success.party_role_ref.id.value
            c.save!
        end
        return true
    end
```

**Comment by ruckus** [comment]
You need to update to Quickeebooks 0.1.5 - I just added that method this morning.

**Comment by bcackerman** [comment]
Can I add that same method for `phone`? So I can write `customer.phone = phone`

**Comment by ruckus** [comment]
I dont have a convenience method available, and I will add it later, but for now you can easily accomplish this yourself by initializing the `phones` array property and adding the `phone` instance to it:

``` ruby

customer.phones = []
customer.phones << phone
```
