### ISSUE TITLE
undefined method `request' error

### ISSUE THREAD

**Issue by bcackerman** [ruckus/quickeebooks#53]
When I try to save my new Qb Online object using `response = customer_service.create(customer)` I receive the error `undefined method 'request' for #<QuickbooksSync:0x007fcc47075fd8>`  Any idea what's up?

**Comment by ruckus** [comment]
Can you please send me your code snippet?

**Comment by bcackerman** [comment]
I call the service from my controller with this code

``` ruby
def quickbooks_sync
    account = current_user.account
    oauth_client = QuickbooksSync.new(account.quickbooks_token, account.quickbooks_secret)
    respond_to do |format|
      if oauth_client.export_customers(account, oauth_client)
        format.html { redirect_to quickbooks_success_users_path }
      end
    end
  end
```

and here's the code in the service object I created to store the information in Quickbooks.

``` ruby
module QBOnline
    def export_customers(account, oauth_client)
        account.customers.each do |c|
            customer_service = Quickeebooks::Online::Service::Customer.new
            customer_service.access_token = oauth_client
            customer_service.realm_id = account.quickbooks_realm_id

            customer = Quickeebooks::Online::Model::Customer.new
            customer.name = c.full_name
            qbemail = Quickeebooks::Online::Model::Email.new
            qbemail.address = c.email
            address = Quickeebooks::Online::Model::Address.new
            address.line1 = c.company
            address.line2 = c.address1
            address.line3 = c.address2
            address.city = c.city
            address.country_sub_division_code = c.state
            address.postal_code = c.zip
            phone = Quickeebooks::Online::Model::Phone.new
            phone.device_type = "Phone"
            phone.free_form_number = c.phone
            fax = Quickeebooks::Online::Model::Phone.new
            fax.device_type = "Fax"
            fax.free_form_number = c.fax

            customer.address = address
            customer.phones = []
            customer.phones << phone
            customer.phones << fax
            customer.email = []
            customer.email << qbemail

            Rails.logger.info oauth_client.inspect
            response = customer_service.create(customer)
            Rails.logger.info response

            c.quickbooks_id = response.success.party_role_ref.id.value
            c.save!
        end
        return true
    end

    def export_invoices
    end

    def import_customers
    end
end

class QuickbooksSync
    def initialize(token, secret)
        oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, token, secret)
    end
    include QBOnline
end
```

Thanks!

**Comment by ruckus** [comment]
Hmm, well the first error message you sent references an undefined "request" - do you have a compete stacktrace for that exception?

But something does look weird with the way you're using the respond_to, I think you have the if expression in the wrong place. You want to put all of your logic in the actual format block.

Instead of :

respond_to do |format|
      if oauth_client.export_customers(account, oauth_client)
        format.html { redirect_to quickbooks_success_users_path }
      end
    end

You want:

respond_to do |format|
  format.html do
    if oauth_client.export_customers(account, oauth_client)
      redirect_to quickbooks_success_users_path and return
    end
  end
end

**Comment by bcackerman** [comment]
Here's the full trace http://d.pr/n/grpj

After changing the format block I still received the same error.

**Comment by ruckus** [comment]
I think part (or maybe the whole) problem is that you have a wrapper object around an oauth client which you're passing to Quickeebooks, but its not _really_ an oauth client access token.

You're passing an instance of your "QuickbooksSync" object to Quickeebooks NOT what it needs which is an instance of OAuth::AccessToken. Which you do create in your class, but its not what is being sent to Quickeebooks.

Refactor your code like so:

class QuickbooksSync
  include QBOnline
  def initialize(token, secret)
    @oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, token, secret)
  end

  def oauth_client
    @oauth_client
  end
end

... then ...

sync = QuickbooksSync.new(account.quickbooks_token, account.quickbooks_secret)
customer_service = Quickeebooks::Online::Service::Customer.new
customer_service.access_token = sync.oauth_client

See what I mean?

**Comment by bcackerman** [comment]
Yeah that works! Thanks so much.

**Comment by bcackerman** [comment]
Ok so that code `c.quickbooks_id = response.success.party_role_ref.id.value` to get the resulting id from Quickbooks is returned is getting this error `undefined method 'success' for #<Quickeebooks::Online::Model::Customer:0x007fbdcc9b1888>`

**Comment by ruckus** [comment]
Yes, my mistake. The response parsing logic for `Online` vs `Windows` is different. The code snippet you're using above is for `Windows` - where the API just returns a basic `Success` or `Error` object with the Object ID.

In your case, using `Online` you will actually get back a populated `Customer` object. 

So you can update your code like so:

``` ruby
created_customer = customer_service.create(customer)
puts "Created Customer ID: #{created_customer.id.value}"
```
