### ISSUE TITLE
Cannot call 'request' method on @oauth

### ISSUE THREAD

**Issue by bhennes2** [ruckus/quickeebooks#6]
When I run this code: 
customer_service = Quickeebooks::Online::Service::Customer.new(oauth_client, realm_id)
customer_service.list 

I receive this error: undefined method `request' for nil:NilClass

It looks like when Quickeebooks::Online::Service::Customer is initialized, it is not setting the access_token to @oauth.

Has anyone else seen this issue?

**Comment by ruckus** [comment]
That style of calling the constructor with those two parameters has been deprecated in favor of a no-arg constructor and use assignments. There should be a `warn()` message outputted to your log with a deprecation notice.

Change your code to:

```
customer_service = Quickeebooks::Online::Service::Customer.new
customer_service.access_token = @oauth_client
customer_service.realm_id = realm_id
customer_service.list
```

This change was to make it easier for stubbing and testing.

**Comment by bhennes2** [comment]
Spot on. +1

**Comment by yul** [comment]
I think you should update README then.

**Comment by ruckus** [comment]
You're right - the README was way out of date and likely confusing people. I just fixed it.

Thanks for the heads up.
