### ISSUE TITLE
The base url constructed is incomplete

### ISSUE THREAD

**Issue by swathinimmala** [ruckus/quickeebooks#7]
When I do this,

 customer = Quickeebooks::Online::Service::Customer.new()
 customer.access_token = access_token
 customer.realm_id = params[:realm]
 p customer.list

I get a 404 not found. Output sample as below:

<pre>
HTTP Error Code: 404, Msg: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body> 
<h1>Not Found</h1>
<p>The requested URL /resource/customers/v2/ was not found on this server.</p>
</body></html>
</pre>

Can you please help me out with this?

**Comment by ruckus** [comment]
It looks like Quickeebooks is not able to determine your base URL. It should be throwing an exception in this case - are you swallowing that exception somewhere? Also, just to make sure is your `params[:realm]` a string and looks something like `"215583939"`?

**Comment by ruckus** [comment]
If you know your base URI you can assign it explicitly to your service object - but just make sure you assign it **before** you assign the `realm_id` (this is annoying order of operations issue that I will be fixing shortly). Like so:

`
s = Quickeebooks::Online::Service::Payment.new
s.access_token = token
s.base_uri = "https://qbo.intuit.com/qbo32"
s.realm_id = "214483922"
s.list
`
This will by-pass the URI determination process.

**Comment by swathinimmala** [comment]
Thanks ruckus! I got it. It was the issue wiith my realm_id.
