### ISSUE TITLE
Fetching data created after certain time

### ISSUE THREAD

**Issue by patrickreiner** [ruckus/quickeebooks#71]
On my first request I fetch ALL data, and I find the largest meta_data.create_time, and store that as well. On subsequent requests, I would like to only fetch records created after that time.

So, for example, my largest meta_data.create_time was 2013-06-05T02:40:28 and I create a filter:

```
[
  StartCreatedTMS :EQUALS: 2013-06-05T02:40:29,
  EndCreatedTMS :EQUALS: 2025-01-01T00:00:00
]
```

When I send the request, I get two records back with the following meta_data.create_time values:

2013-06-05 02:40:28
2013-06-05 02:39:21

Notice how both times are outside of the range I requested in my filter.

I am not sure why this is happening. I wouldn't think time zone would be an issue because I am taking the meta_data.create_time, storing it, and then using that same value to generate the filter for my next request.

Do you have any idea what is going on here?

**Comment by ruckus** [comment]
Not sure whats happening off the top of my head. My first thought is that it _could_ be a time zone issue. 

Try using the API explorer:

https://developer.intuit.com/apiexplorer?apiname=V2QBD

And monkeying around with specifying times. Check out this page:

https://developer.intuit.com/docs/0025_quickbooksapi/0050_data_services/v2/0500_quickbooks_windows/0100_calling_data_services/0015_retrieving_objects

(Scroll down to "Time Filters in Data Services").

This sentence stands out:

"For example, if the request specifies the StartCreatedTMS as 2011-07-28T17:00:00.0 (with no time zone designation), the XML parser will assume that value is PST"

## 

As a quick test open up `Quickeebooks::Shared::Service::Filter` and change DATE_TIME_FORMAT to:

DATE_TIME_FORMAT = '%Y-%m-%dT%H:%M:%SZ'

(just add the trailing 'Z') 

and try again.

**Comment by patrickreiner** [comment]
Thanks for the links. This seems to be an issue on Intuit's end, I will report this to them. See attached image.
![1370542860 948590](https://f.cloud.github.com/assets/5597/619787/e726eb6e-ced5-11e2-9fe9-99e17c9e8664.png)

**Comment by patrickreiner** [comment]
Intuit has confirmed that this a bug on their end, please see email below:

From: IPP Developer Support Routing ippdevelopersupport@intuit.com
Subject: Case 00003613: API fetching results outside of query parameters [ ref:_00DG0COk8._500G0E5QEv:ref ]
Date: June 10, 2013 3:51:27 AM MST

Hello Patrick,   

The time part of 'StartCreatedTMS' is not working. It is a bug in our system. We have raised a bug ticket for this. At present, we don't have any ETA of this fix. Sorry for the inconvenience.

Sincerely,

Manas Mukherjee 
Intuit
