### ISSUE TITLE
Concept of 'syncing' the Desktop flavor

### ISSUE THREAD

**Issue by theinventor** [ruckus/quickeebooks#76]
Hey guys - I LOVE how this project is progressing :)

We've been using the Online service in production for a couple months now, works great.

We have a concept of 'syncing' an invoice, when we add line items in our app, we have the Quickbooks Invoice_ID on our model, and we find the item and re-sync it to be sure it has all the line items.

How do you do this with the Windows/Desktop version? The create doesn't give back a record ID.

I get a success, so I can then go do a service.list and look for the invoice number  - is that what everyone is doing?

It would be awesome if the online invoice.create and desktop invoice.create returned an object with similar methods/data

**Comment by ruckus** [comment]
A successful Invoice creation returns XML like:

``` xml
<RestResponse xmlns="http://www.intuit.com/sb/cdm/v2">
    <Success RequestId="b42f3cc25ca74ee59a76515ec0734f28">
        <ObjectRef>
            <Id idDomain="NG">1208839</Id>
            <SyncToken>1</SyncToken>
            <LastUpdatedTime>2013-06-21T15:50:32Z</LastUpdatedTime>
        </ObjectRef>
        <RequestName>InvoiceAdd</RequestName>
        <ProcessedTime>2013-06-21T15:50:32Z</ProcessedTime>
    </Success>
</RestResponse>
```

And your newly created Invoice ID is the value in the `Id` element.

In Quickeebooks that is handled by the `RestResponse` model like so:

``` ruby

> response = invoice_service.create(invoice)
> response.success?
=> true
> puts "Invoice ID: #{response.success.object_ref.id}"
=> Invoice ID: 1208839
```

Does that help?

**Comment by theinventor** [comment]
Ah, yes - it does

This interface is a little different than the response of the Online version - and I just noticed the table on the readme about Desktop not supporting fetch_by_id and update

I'll just treat desktops users as second class citizens :)
