### ISSUE TITLE
Create Vendor throws validation error

### ISSUE THREAD

**Issue by kirley** [ruckus/quickeebooks#77]
Hi There,

I'm trying to create a vendor record and my code is throwing a vendor validation error:  

```
 Validation failed: Country can't be blank, Address 1 can't be blank, City can't be blank
```

The odd thing is that the vendor is actually created correctly into QBO and the address is there as well.  I have tried this with several different vendors all resulting in the same error.  I suppose I could work around this if quickeebooks wasn't throwing an error but since it is I don't get the vendor id back in the response and I need it for my code to function properly.  Any advice on this would be greatly appreciated!  Here is my Create Vendor code snippit:

```
   vendor_service = Quickeebooks::Online::Service::Vendor.new
    vendor_service.access_token = @access_token
    vendor_service.realm_id = @realm
    vendor_service

    v = Quickeebooks::Online::Model::Vendor.new
    v.name = affiliate_account.payee_name

    address = Quickeebooks::Online::Model::Address.new
    address.line1 = affiliate_account.address_1
    address.line2 = affiliate_account.address_2
    address.city = affiliate_account.city
    address.country_sub_division_code = affiliate_account.state
    address.postal_code = affiliate_account.postal_code
    address.country = affiliate_account.country.name
    address.tag = "Billing"
    v.address = address

    response = vendor_service.create(v)
    affiliate_account.quickbooks_vendor_id = response.id.value
```

**Comment by ruckus** [comment]
I'm confused, you can or cannot create the Vendor? You say you try and create a Vendor but get a validation error. Then a little later you say:

`The odd thing is that the vendor is actually created correctly into QBO and the address is there as well.`

You mean the Vendor exists because you have created it in QB online yourself (manually) or you have created it using Quickeebooks?

Your code looks good and taking it verbatim and running it successfully creates a Vendor. For duplicity sake I'm using:

``` ruby

intuit_account = IntuitAccount.find(37)
vendor_service = Quickeebooks::Online::Service::Vendor.new
vendor_service.access_token = intuit_account.consumer
vendor_service.realm_id = intuit_account.realm_id

v = Quickeebooks::Online::Model::Vendor.new
v.name = "My Vendor"

address = Quickeebooks::Online::Model::Address.new
address.line1 = "123 Main"
address.line2 = "Suite A"
address.city = "San Jose"
address.country_sub_division_code = "CA"
address.postal_code = "94117"
address.country = "US"
address.tag = "Billing"
v.address = address

response = vendor_service.create(v)
2.0.0p247 :043 > response.id.value
 => "112"
```

**Comment by ruckus** [comment]
Turns out that an Address is **not** required when creating a Vendor. This works too:

``` ruby

intuit_account = IntuitAccount.find(37)
vendor_service = Quickeebooks::Online::Service::Vendor.new
vendor_service.access_token = intuit_account.consumer
vendor_service.realm_id = intuit_account.realm_id
vendor_service

v = Quickeebooks::Online::Model::Vendor.new
v.name = "My Vendor222"
response = vendor_service.create(v)

2.0.0p247 :053 > response.id.value
 => "113"
```

**Comment by kirley** [comment]
I'm really sorry to waste your time Ruckus, this gem has been a great help.  My code was throwing an error but you helped me identify that it wasn't coming from Quickbooks.  Thank you!

**Comment by ruckus** [comment]
No problem, glad you got it figured out. Yeah as I was monkeying around last and deduced that QBO doesnt require Country / Address / City (and when it does require fields the actual message is not that Rails-style), well I had the thought it was in fact your Rails model that was failing validation. I should have said something... sorry!
