### ISSUE TITLE
Add ShowAs to Vendor Model

### ISSUE THREAD

**Issue by kirley** [ruckus/quickeebooks#78]
I realized that the show_as / ShowAs attribute on the Vendor model seems to be missing.  Would it be possible to include this field?  I would assume others might also benefit from this field since is used to define the name that shows up on checks when something other than the actual vendor name is needed on the check.

I believe the fix would only require one line of code in the lib/quickeebooks/common/online_entity_model.rb

```
xml_accessor :show_as, :from => 'ShowAs'
```

Thanks!

**Comment by kirley** [comment]
The attribute external_id / ExternalId attribute also seems to be missing.

**Comment by ruckus** [comment]
Cool, just released `0.1.12` with both of those attributes added. Next time feel free to send a Pull-Request :)

**Comment by kirley** [comment]
Thanks, i'll send a pull request next time for sure.
