### ISSUE TITLE
How to extract the required data from the collection 

### ISSUE THREAD

**Issue by swathinimmala** [ruckus/quickeebooks#8]
I did the customer.list and I get a huge chunk of data. I see that you are parsing the xml response too. 
How should I handle the collection to get the details of a particular customer?
Can you please help me out with this?

**Comment by ruckus** [comment]
Well if you already know the Customer `ID` (Intuit's, not your own) than you can find the Customer directly by using `fetch_by_id` on the service.

But if you don't know the ID then you will need to fetch all and filter them in Ruby. As you can see the result of `list` is a Hash with keys of `entries`, `count` and `current_page`. `entries` is an array of `Customer` model objects. 

Thus if you're looking for a customer named `ABC Plumbing` you can find it like so:

```
customers = customer_service.list
customer = nil
if customers.entries.any?
   customer = customers.entries.find { |rec| rc.name == 'ABC Plumbing' }
end
```
