### ISSUE TITLE
Quickbooks Desktop, new customer needs domain="NG" not "QB"

### ISSUE THREAD

**Issue by theinventor** [ruckus/quickeebooks#85]
I asked intuit about this, I'm trying to get an invoice created for a new customer, with the desktop flavor.

I create a customer, I get an ID of: 849630, using charles I was able to get this;
            <Id idDomain="NG">849630</Id>

It seems attaching this ID to a new invoice results in;
p_validate_txn - unable to find MBL customer REF id = 849630 idDomain = QB

I asked support and they said I need to use NG as the domain.

Looking at lib/quickeebooks/windows/model/id.rb

It seems there is only support for querying by the QB domain, not NG - are others seeing this?

Intuit said 'for a new customer that hasn't synced, use the NG domain'

Here is their full response;
-------- from intuit ----------
Please read this information about domains (idDomain):
NG -
Records created in the cloud (via the API) have an NG domain, which is basically their unsyncronized primary key. The records which are created by apps that call data services have this NG ID

QB-
Once they get synced to QuickBooks desktop, they then get a QB domain ID value as well (the QB ID is the syncronized primary key from within QuickBooks).
Records created by QB desktop have QB ID
You should be able to refer to any record by either the NG or QB ID.

QBO -
Records created by QB Online have QBO ID.

In your invoice query, you should be referencing the customer as <Id idDomain="NG">849630</Id> but you are passing <CustomerId idDomain="QB">849630</CustomerId>.

Any entity gets created in the cloud/API explorer/code will have NG domain and after a successful sync they will get ExteranlKey with IDDomain QB value too.

So, since your data is not synched, please use NG domain id for referencing customer for creating Invoice.

----------- end intuit ----------

So now, I've done some syncs.. I use the customer_service.list and I can see this customer, they show up in Quickbooks, but, they still only have an NG ID on them.

It almost seems I need to store the fact that they are 'NG' - and use that for all future queries..

This seem right???

**Comment by theinventor** [comment]
OH!

@customer_service.fetch_by_id(849630, 'NG')

So I can find the customer, still, putting this ID on an invoice doesn't let me create it..

There is some code in Windows::Model::Id,

```
    def initialize(value = nil, suppress_domain_attribute = false)
      unless suppress_domain_attribute
        self.idDomain = DOMAIN
      end
      self.value = value
    end
```

Is using this suppress_domain_attribute part of the answer?

-- EDIT --

I see when I make the invoice, and I add the ID model for the customer_id, I can specify the id.idDomain = 'NG' - that works.

I guess I have to write a bit of code to detect which works, and add the right domain

**Comment by ruckus** [comment]
To be honest I have forgotten about `suppress_domain_attribute` and being able to supply a 2nd argument to `fetch_by_id`. But this does vaguely ring a bell. I don't see it myself since all the Invoices I create I use a QB customer that has long ago been created in the cloud from QB Desktop originally (that is, I never create Customers myself, just use existing ones). 

But I can understand your issue. I find it incredibly lame that QB has a different ID structure depending on how the Customer was created. I can feel your pain.

**Comment by ruckus** [comment]
Closing this?
