### ISSUE TITLE
Way to push jobs in quickbook using Online models??

### ISSUE THREAD

**Issue by przbadu** [ruckus/quickeebooks#98]
I have already pushed invoice and customers to the quickbook and I am also able to pull items from quickbooks to my rails app using quickeebooks gem.

Can i push Jobs to QBO using quickeebook gem? I am using Quick Book Online not Desktop version. But in Quickeebook::Online::Model job is not present. I also want to push sub-customers to the quickbook account. But, i think,  that also can be done through Job model only.

Now i am really stuck in this  point. Any suggestions please, to solve this problem??

Thanks in advance

**Comment by ruckus** [comment]
I just released `0.1.20` with support for `Online#Job`

**Comment by przbadu** [comment]
Thanks a lot... :+1:
