### ISSUE TITLE
Bluedot Menu displaying "We are sorry but we cannot load the menu right now"?

### ISSUE THREAD

**Issue by przbadu** [ruckus/quickeebooks#99]
``` ruby

<script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>

<script>
  intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: "<%= authenticate_settings_url %>"});
</script>

<body>
  <ipp:blueDot></ipp:blueDot>
</body>

```

It is displaying bluedot menu on the top of my application but not displaying the companies that i am connected with. Insteed, it is displaying something like "We are sorry but we cannot load the menu right now".

I want to display the companies list that I am connected with in this blue dot menu. I think i am missing path of munuProxy :

``` ruby
menuProxy: '/path/to/blue-dot'
```

I have no idea what to do with this. If i have to give path to any bluedotMenu action than what should i write on that action to display list of companies?

[NOTE: I am using Chrome and Firefox as my browser so, i don't think it's my browser problem]

**Comment by przbadu** [comment]
Fault was all mine. Now, I have modified menuProxy to: 

``` ruby
<script>
  intuit.ipp.anywhere.setup({menuProxy: '<%= bluedot_settings_url %>', grantUrl: "<%= authenticate_settings_url %>"});
</script>
```

"We are sorry but we cannot load the menu right now", this was displaying because I forgot to create .js file of bluedot action.

Now it is displaying bluedot menu without companies. So, I need a help to load companies in this bluedot menu from .js file or bluedot action?

**Comment by ruckus** [comment]
You will need to retrieve the contents of the Bluedot menu from Intuit. Intuit also recommends you cache the output. An example Rails controller (your `bluedot_settings_url`) might look like:

``` ruby
class IntuitController < ApplicationController

  def bluedot
    intuit_account = IntuitAccount.find(..)

    # check first in cache
    html = Rails.cache.read(intuit_account.menu_proxy_code_id)
    if !html.blank?
      render(:text => html) and return
    end

    # not cached, retrieve from Intuit
    access_token = intuit_account.access_token
    access_secret = intuit_account.access_secret
    consumer = OAuth::AccessToken.new($qb_oauth_consumer, access_token, access_secret)
    response = consumer.request(:get, "https://appcenter.intuit.com/api/v1/Account/AppMenu")
    if response && response.body
      html = response.body

      # insert into cache
      if intuit_account
        Rails.cache.write(intuit_account.menu_proxy_code_id, html)
      end
      render(:text => html) and return
    end
  end

end
```

**Comment by przbadu** [comment]
How can I get menu_proxy_code_id? I have no idea. 

I tried to generate menu_proxy_code_id while generating realm_id, access_token and access_secrete like:

``` ruby
at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    access_token = at.token
    access_secret = at.secret
    realm_id = params['realmId']

    menu_proxy_code_id = at.menu_proxy_code_id
    puts "*************" + menu_proxy_code_id +"******************"
```

but it will generate something like:

``` ruby
NoMethodError - undefined method `menu_proxy_code_id' for #<OAuth::AccessToken:0xb4eac7c>:
```

What i am missing here. Please make me clear, how can I generate menu_proxy_code_id and display contents of the bluedot menu.

thanks

**Comment by przbadu** [comment]
thanks the solution was in your post that i was not focusing at:

``` ruby
    # not cached, retrieve from Intuit
    access_token = intuit_account.access_token
    access_secret = intuit_account.access_secret
    consumer = OAuth::AccessToken.new($qb_oauth_consumer, access_token, access_secret)
    response = consumer.request(:get, "https://appcenter.intuit.com/api/v1/Account/AppMenu")
    if response && response.body
      html = response.body
      render(:text => html) and return
   end
```

Really apprreciate for your help.
